---
title: "Reproducible Research: Peer Assessment 1"
author: "Hari"
date: "15 January 2017"
output: html_document
#keep_md: true
---


## Loading and preprocessing the data
```{r}
datafname = "activity.csv"
zipfname = "repdata data activity.zip"  # this file should be placed in the working directory
if (!file.exists(datafname)){
  unzip(zipfname)
}

# load required libraries
library(lattice)
library(knitr)
```
```{r}
# Read data from activity.csv using read.csv function
actdata<-read.csv("activity.csv", header=TRUE, colClasses=c("numeric","Date","numeric"))

# Print first few rows of data (this will give details of the columns)
head(actdata)

#Display quick summary of the data loaded
summary(actdata)

#initialize min and max 
mindt <- min(actdata$date)
maxdt <- max(actdata$date)
durindays <- as.numeric(maxdt - mindt) + 1
```
```{r}
## What is mean total number of steps taken per day?

#Remove rows with missing values
cmpl_actdata<-actdata[complete.cases(actdata),] # data with only non-missing rows

count_cmpl_cases<-nrow(cmpl_actdata)

# Missing data
incmpl_actdata<-actdata[!complete.cases(actdata),] ## data with only missing rows
count_incmpl_cases<-nrow(incmpl_actdata)

# Number of steps per day
stps_per_day <- as.data.frame(tapply(cmpl_actdata$steps, INDEX = cmpl_actdata$date, FUN = "sum", na.rm = TRUE))
colnames(stps_per_day) <-  "steps"
# maximum number of steps among all the dates + some buffer to label x-axis
max_num_steps<-max(stps_per_day)+5000
# plot histogram of frequency of the steps
hist(stps_per_day$steps, main = "Total Number of Steps Per Day", 
     xlab = "Total Number of Steps Per Day", ylab = "Frequency", 
     breaks = 10, xlim = c(0, max_num_steps), ylim = c(0, 20), col = "green")

#Calculate and report the mean and median total number of steps taken per day

mean_num_steps <- format(mean(stps_per_day$steps, na.rm = TRUE), big.mark=",",scientific=F)
median_num_steps <- format(median(stps_per_day$steps, na.rm = TRUE),big.mark=",",scientific=F)

## What is the average daily activity pattern?

# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, 
# coveraged across all days (y-axis)
#calculate average number of steps by intervals without missing values
avg_num_stps_intvl <- as.data.frame(tapply(cmpl_actdata$steps, 
                                           INDEX = cmpl_actdata$interval, 
                                           FUN = "mean", na.rm = TRUE))
#Name the column as avg_steps
colnames(avg_num_stps_intvl) <- "avg_steps"

#Name rownames to interval
avg_num_stps_intvl$interval <- rownames(avg_num_stps_intvl)
row.names(avg_num_stps_intvl)<-NULL

#display few observations from the top
head(avg_num_stps_intvl)

#Plot a line graph of avg number of steps with 5-min interval 

plot(avg_num_stps_intvl$interval, avg_num_stps_intvl$avg_steps, type = "l", 
     xlab = "Time Interval (5-mins)", ylab = "Average number of steps", 
     main = "Average Number of Steps by Time  Interval", col="blue")
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
#Based on the above data analysis and trends we can see that the 5-miniutes interval with maximum number of average steps per day is 835.

## Imputing missing values
#Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
# Missing data
incmpl_actdata<-actdata[!complete.cases(actdata),] ## data with only missing rows
count_incmpl_cases<-nrow(incmpl_actdata)

# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
#calculate median number of steps by intervals without missing values
median_stps_intvl <- as.data.frame(tapply(cmpl_actdata$steps, 
                                          INDEX = cmpl_actdata$interval, 
                                          FUN = "median", na.rm = TRUE))
#Name calculated median column to median_steps
colnames(median_stps_intvl) <- "median_steps"
#Name rownames to interval 
median_stps_intvl$interval <- rownames(median_stps_intvl)
row.names(median_stps_intvl)<-NULL
mean_median<-merge(median_stps_intvl,avg_num_stps_intvl, by="interval")
#merge mean and median 
actdata_with_sum<-merge(actdata,mean_median, by="interval")
head(actdata_with_sum)

#Create a new dataset that is equal to the original dataset but with the missing data filled in.

for (i in (1:nrow(actdata_with_sum))) {
  if (is.na(actdata_with_sum$steps[i])) {
    actdata_with_sum$steps[i] <- actdata_with_sum$median_steps[i]
  } 
}

actdata_no_miss<-actdata_with_sum[, c("steps","date", "interval")]
summary(actdata)

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number #of steps taken per day. 
# Number of steps on a particular date
stps_per_day_nm <- as.data.frame(tapply(actdata_no_miss$steps, INDEX = actdata_no_miss$date, FUN = "sum"))
colnames(stps_per_day_nm) <-  "steps"
# maximum number of steps among all the dates + some buffer to label x-axis
max_num_steps<-max(stps_per_day_nm)+5000
# plot histogram of frequency of the steps
hist(stps_per_day_nm$steps, main = "Total Number of Steps Per Day", 
     xlab = "Total Number of Steps Per Day", ylab = "Frequency", 
     breaks = 10, xlim = c(0, max_num_steps), ylim = c(0, 20), col = "blue")

mean_num_steps_nm <- format(mean(stps_per_day_nm$steps), big.mark=",",scientific=F)
median_num_steps_nm <- format(median(stps_per_day_nm$steps),big.mark=",",scientific=F)

#Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date #is a weekday or weekend day.

# Logical variable - weekdays: Saturday and Sunday would be TRUE else FALSE
actdata_no_miss$weekdays <- grepl("^[Ss]", weekdays(as.Date(actdata_no_miss$date)))

for (i in (1:nrow(actdata_no_miss))) {
  if (actdata_no_miss$weekdays[i] == TRUE) {
    actdata_no_miss$week_day_factor[i] <- "weekend"
  } else {
    actdata_no_miss$week_day_factor[i] <- "weekday"
  }
}
#Check first few records
head(actdata_no_miss)

## Are there differences in activity patterns between weekdays and weekends?
```
